### ISSUE TITLE
Error running 'Processing.py': Python script path must be set

### ISSUE THREAD

**Issue by mayjack0312** [Abdulla060/Processing.py-intellisense#8]
Error running 'Processing.py': Python script path must be set

**Comment by mayjack0312** [comment]
java -jar lib/processing-py.jar .\py.py
Traceback (most recent call last):
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\site.py", line 585, in <module>
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\site.py", line 567, in main
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\site.py", line 300, in addusersitepackages
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\site.py", line 289, in getusersitepackages
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\sysconfig.py", line 416, in get_path      
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\sysconfig.py", line 407, in get_paths     
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\sysconfig.py", line 180, in _expand_vars  
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\sysconfig.py", line 154, in _subst_vars
  File "D:\Processing.py-intellisense-master\lib\processing-py.jar\Lib\sysconfig.py", line 154, in _subst_vars
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)

**Comment by mayjack0312** [comment]
![image](https://github.com/Abdulla060/Processing.py-intellisense/assets/102800660/5e7e90ac-3694-4e42-a1f9-101f43ea9612)
![image](https://github.com/Abdulla060/Processing.py-intellisense/assets/102800660/c0e9468c-d9fe-4ec1-ba35-6d7e3a77a637)
![image](https://github.com/Abdulla060/Processing.py-intellisense/assets/102800660/b80e59ea-dba5-40ee-8cd3-ab95745723e3)
